### ISSUE TITLE
esp-isa-sim doesn't appear to enable hwacha instruction set

### ISSUE THREAD

**Issue by lluixhi** [ucb-bar/esp-isa-sim#3]
I was trying to verify whether some code that I wrote using hwacha was correct, but using
`spike --extension=hwacha pk ./test` resulted in `An illegal instruction was executed!`.

The instruction encountered was `insn 0000200b` which is `vsetcfg zero`, the first hwacha instruction in my program. Am I calling spike incorrectly or is there some other issue?

**Comment by chenzhen1998roy** [comment]
Hi  lluixhi,

How did you solve this issue finally? Could you share me some instruction for running hwacha instruction in spike?

Best Regard,
Roy

**Comment by colinschmidt** [comment]
For using `pk` I recently updated `esp-tools` to enable this by default:
https://github.com/ucb-bar/esp-tools/commit/dcb6012f77101e793948cc90ac31b3735a9f3f6d
